version: '3'
services:
  app:
    build: .
    command: "python wsgi.py"
    links:
      - mongodb
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - mynet
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    hostname: test_mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - mynet
  
networks:
    mynet:
      name: mynet